name: Application CI
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - name: Get dependencies
      run: flutter pub get
    - name: Start release build
      run: flutter build appbundle
    - name: Run tests
      run: flutter test